<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-LGR4B9K" failures="1" tests="5" name="PersonalLoan" time="0.076" errors="0" timestamp="2023-09-24T12:52:47 PDT">
  <testcase classname="target.Basics2" name="personalLoan" time="0.008"/>
  <testcase classname="target.Basics4" name="LoginAPIhomeLoan" time="0.006"/>
  <testcase classname="target.Basics4" name="MobileLoginhomeLoan" time="0.002"/>
  <testcase classname="target.Basics4" name="WebloginhomeLoan" time="0.001"/>
  <testcase classname="target.TestNGBasicsClass1" name="Demo2" time="0.033">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at target.TestNGBasicsClass1.Demo2(TestNGBasicsClass1.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo2 -->
  <testcase classname="target.TestNGBasicsClass1" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- PersonalLoan -->
